//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public int ParentId { get; set; }
        public string MenuPath { get; set; }
        public string URL { get; set; }
        public string Icon { get; set; }
    }
}
