//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int CustomId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Number { get; set; }
        public int GoodsId { get; set; }
    
        public virtual Custom Custom { get; set; }
        public virtual GoodsInfo GoodsInfo { get; set; }
    }
}
