//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLog
    {
        public long RecordId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string OperatDetail { get; set; }
        public string Operater { get; set; }
    }
}
