//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public int RefundId { get; set; }
        public int ClientId { get; set; }
        public System.Guid OrderId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> DealTime { get; set; }
        public string Remark { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Client Client { get; set; }
    }
}
